---
title: "Latest Updates"
author: "Lena Schmidt"
date: "March 21st, 2023"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

Latest published version: [ Data extraction methods for systematic review (semi)automation: A living systematic review (version 1; peer review: 3 approved)](https://f1000research.com/articles/10-401)

This page contains the latest updates to this living review. We have screened and continued the work on this review, a status update and resources are given below.

Current literature updates, extraction progress and duplicates are accessible by clicking on the relevant fields of the PRISMA2020 diagram.

### Screening status after publication of base-review

Latest references retrieved: Dec 6th 2022 ([PubMed](https://pubmed.ncbi.nlm.nih.gov/), [cs arXiv](https://arxiv.org/archive/cs), [ACL](https://aclanthology.org/), [DBLP](https://dblp.org/)) Mar 21 2023 ([EPPI-Reviewer Microsoft Academic](https://eppi.ioe.ac.uk/cms/er4/Manuals/MicrosoftAcademicGraphinEPPI-Reviewer/tabid/3754/Default.aspx))

Number of abstracts retrieved (post base-review): 10,108 

Number of abstracts after duplicates removed: 9,338

Number of abstracts screened: 9,338

Number of abstracts sent for full-text assessment: 164


Number of full-texts included: 23

Number of full-texts excluded: 141

<!-- ### PRISMA 2020 flow diagram for the review update -->

<!-- This is the incomplete PRISMA diagram for the first update of this living review (work in progress, see base review for published results). Clicks on the boxes redirect to the in-progress files and data. -->

<!-- ```{r, echo=FALSE} -->
<!-- htmltools::includeHTML("figures/new_prisma.html") -->

<!-- ``` -->

<!-- The PRISMA diagrams were created using [Haddaway, NR. 2020. SRflowdiagram: flow charts for systematic reviews and maps. doi: 10.5281/zenodo.4134795](https://zenodo.org/record/4134795#.X67YUlCnxaQ) -->

<!-- ### Latest figures -->

<!-- These figures represent pre-update, and therefore unpublished, content from the living review.  -->

<!-- ```{r, echo=FALSE} -->
<!-- htmltools::includeHTML("figures/bar_System_architectures.html") -->
<!-- htmltools::includeHTML("figures/bar_App_or_user_interface_availability.html") -->
<!-- htmltools::includeHTML("figures/year_bar.html") -->
<!-- ``` -->





