---
title: "Publications"
author: "Lena Schmidt"
date: "March 11, 2025"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Publication of our living systematic review update

The most recent published version on F1000 research is [ Data extraction methods for systematic review (semi)automation: Update of a living systematic review](https://f1000research.com/articles/10-401). Please cite as:

> <font size="2" color="gray">Schmidt L, Finnerty Mutlu AN, Elmore R et al. Data extraction methods for systematic review (semi)automation: Update of a living systematic review [version 2; peer review: 3 approved]. F1000Research 2023, 10:401 (https://doi.org/10.12688/f1000research.51117.2) </font> 

## Evidence-Based Toxicology commentary (pre-print) discussing LLM data from LSR update 

This pre-print related to the LSR is currently under review, it is accessible here: [Large Language Models for Data Extraction in Toxicology: Implications and Lessons Learned from the Clinical Evidence Domain](https://zenodo.org/records/14893134)

> <font size="2" color="gray">Schmidt, L., Campbell, F., Craig, D., Walker, V. R., Rooney, A. A., Schmitt, C. P., Hartung, T., & Thomas, J. (2025). Large Language Models for Data Extraction in Toxicology: Implications and Lessons Learned from the Clinical Evidence Domain (Version 1). Zenodo. https://doi.org/10.5281/zenodo.14893134 </font> 


## Other
The review protocol was published via F1000 research as [Data extraction methods for systematic review (semi)automation: A living review protocol](https://f1000research.com/articles/9-210). Please cite as:

> <font size="2" color="gray">Schmidt L, Olorisade BK, McGuinness LA et al. Data extraction methods for systematic review (semi)automation: A living review protocol [version 2; peer review: 2 approved]. F1000Research 2020, 9:210 (https://doi.org/10.12688/f1000research.22781.2)</font> 

The up-to-date code for the screening and literature retrieval application is available from [L-ENA's GitHub repository](https://github.com/L-ENA/SR_automation_LSR) or as release on [zenodo](https://zenodo.org/record/3871366#.XteMf-fTU2w). Please cite as:

> <font size="2" color="gray">Luke McGuinness and Lena Schmidt. mcguinlu/COVID_suicide_living: Initial Release (Version v1.0.0). Zenodo 2020. Available from: http://doi.org/10.5281/zenodo.3871366</font> 

The review was registered prospectively on the OSF on March 9th 2020 under DOI [10.17605/OSF.IO/ECB3T](https://osf.io/ecb3t)




```{r}

```

